import * as headerHome from './js/header-home';
import * as modal from './js/modal';
import * as popular from './js/popular';
import * as loader from './js/loader';
import * as search from './js/search-movie';
import * as pagination from './js/pagination-home';
import { onScroll, onToTopBtn } from './js/scroll-to-top';
onScroll();
onToTopBtn();
import * as firebase from './js/firebase';
